inertial_frame_id: world
waypoints:
  -
    point: [-40, -40, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-40, -50, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-50, -100, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-60, -80, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-60, -70, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-60, -56, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-100, -56, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [-150, -80, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
