<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Loading some constants -->
  <xacro:include filename="$(find uuv_descriptions)/urdf/common.urdf.xacro"/>
  <!-- Loading file with sensor macros -->
  <xacro:include filename="$(find uuv_sensor_ros_plugins)/urdf/sensor_snippets.xacro"/>
  <!-- Loading the UUV simulator ROS plugin macros -->
  <xacro:include filename="$(find uuv_gazebo_ros_plugins)/urdf/snippets.xacro"/>
  <!-- Loading vehicle's specific macros -->
  <xacro:include filename="$(find nukhada_description)/urdf/snippets.xacro"/>

  <xacro:include filename="$(find nukhada_description)/urdf/hull.xacro" />

  <!--
    Vehicle's parameters (remember to enter the model parameters below)
  -->

  <xacro:property name="mass" value="0"/>
  <!-- Center of gravity -->
  <xacro:property name="cog" value="0 0 0"/>
  <!-- Fluid density -->
  <xacro:property name="rho" value="1028"/>

  <!-- Properties -->
  <xacro:property name="length" value="1" />
  <xacro:property name="width" value="0.55" />

  <xacro:property name="hull_length" value="1" />
  <xacro:property name="hull_width" value="0.15" />
  <xacro:property name="hull_height" value="0.15" />

  <xacro:property name="width_between_hulls" value="0.25" />

  <xacro:property name="pod_altitude" value="0.17" />
  <xacro:property name="pod_length" value="0.1" />
  <xacro:property name="pod_radius" value="0.05" />

  <xacro:property name="propeller_length" value="0.05" />
  <xacro:property name="propeller_radius" value="0.05" />

  <!-- Vehicle macro -->
  <xacro:macro name="nukhada_base" params="namespace *gazebo">

    <!-- Rigid body description of the base link -->
    <link name="${namespace}/base_link">
      <gazebo reference="${namespace}/base_link">
        <selfCollide>false</selfCollide>
      </gazebo>
    </link>

    <link name="chassis">
      <!--<xacro:inertia_cuboid m="10" h="0.15" w="0.15" l="0.15" />-->
      <inertial>
                <mass value="30" />
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.0000000" ixy="0.0" ixz="0.0"
                    iyy="0.0000000" iyz="0.0"
                    izz="0.0000000" />
            </inertial>
      <visual>
        <origin xyz="0 0 0.17" rpy="0 0 0" />
        <geometry>
          <box size="1 ${width_between_hulls+hull_width*2} 0.15" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0.17" rpy="0 0 0" />
        <geometry>
          <box size="1 ${width_between_hulls+hull_width*2} 0.15" />
        </geometry>
      </collision>
    </link>

    <!-- Set up hydrodynamic plugin given as input parameter -->
    <xacro:insert_block name="gazebo"/>
    <!-- Include the thruster modules -->
    <xacro:include filename="$(find nukhada_description)/urdf/actuators.xacro"/>

    <!-- Include the sensor modules -->
    <xacro:include filename="$(find nukhada_description)/urdf/sensors.xacro"/>

    <joint name="base_link_to_chassis" type="fixed">
      <parent link="${namespace}/base_link" />
      <child link="chassis" />
    </joint> 

    <xacro:hull robot_namespace="${namespace}" parent_link="chassis" prefix="port" reflect="1" thruster_id="0"/>
    <xacro:hull robot_namespace="${namespace}" parent_link="chassis" prefix="starboard" reflect="-1" thruster_id="1"/>
  </xacro:macro>
</robot>
