<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

        <xacro:include filename="$(find nukhada_description)/urdf/pod.xacro" />

    <xacro:macro name="hull" params="robot_namespace parent_link prefix reflect thruster_id">

        <link name="hull_${prefix}">

            <visual>
                <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
                <geometry>
                    <cylinder length="${hull_length}" radius="${hull_height/2}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
                <geometry>
                    <cylinder length="${hull_length}" radius="${hull_height/2}"/>
                </geometry>
            </collision>

            <xacro:inertia_cylinder m="5" r="${hull_height/2}" l="${hull_length}" />
            <!--<inertial>
                <mass value="5" />
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.0000000" ixy="0.0" ixz="0.0"
                    iyy="0.0000000" iyz="0.0"
                    izz="0.0000000" />
            </inertial>-->

        </link>

        <joint name="${parent_link}_to_${prefix}_hull" type="fixed">
            <parent link="${parent_link}" />
            <child link="hull_${prefix}" />

            <origin xyz="0 ${reflect*width_between_hulls} 0" />
        </joint>

         <xacro:pod 
            robot_namespace="${robot_namespace}"
            parent_link="hull_${prefix}" 
            prefix="${prefix}"
            thruster_id="${thruster_id}" />

    </xacro:macro>

</robot>
