repositories:
  catkin_simple:
    type: git
    url: https://github.com/catkin/catkin_simple.git
    version: 0e62848b12da76c8cc58a1add42b4f894d1ac21e
  asv_wave_sim:
    type: git
    url: https://github.com/srmainwaring/asv_wave_sim.git
    version: f670bbc738e609f61f94e0f4fe496d5b6909c7bd
  uuv_manipulators:
    type: git
    url: https://github.com/Field-Robotics-Lab/uuv_manipulators.git
    version: e2cf9d24afd6c2b33fadf637d88a111c1fa9f578
  uuv_simulation_evaluation:
    type: git
    url: https://github.com/uuvsimulator/uuv_simulation_evaluation.git
    version: 9e58bf3f93ede1a8a9674aeb3f12ec1c184b9fb5
  rexrov2:
    type: git
    url: https://github.com/uuvsimulator/rexrov2.git
    version: 1546681610ce0d3a921447bb7d176a74967eea56
  eca_a9:
    type: git
    url: https://github.com/uuvsimulator/eca_a9.git
    version: 5c7e357253c0873d1441ae10910949871cfb944a